In [5]:
## script para extrair Dummy Features da base de digitos manuscritos
## As imagens sao normalizadas no tamanho indicado nas variavies X e Y
## Aprendizagem de Maquina, Prof. Luiz Eduardo S. Oliveira
##
##
import sys
import cv2
import os
import numpy as np
import random

def load_images(path_images, fout, X, Y):
	print ('Loading images...')
	archives = os.listdir(path_images)
	images = []
	arq = open('digits/files.txt')
	lines = arq.readlines()
	print ('Extracting dummy features')
	for line in lines:
		aux = line.split('/')[1]
		image_name = aux.split(' ')[0]
		label = line.split(' ')[1]
		label = label.split('\n')
		
		for archive in archives:
			if archive == image_name:
				image = cv2.imread(path_images +'/'+ archive, 0)
				rawpixel(image, label[0], fout, X, Y)
				
				#images.append((image, label))

	print ('Done!')
	return images

#########################################################
# Usa o valor dos pixels como caracteristica
#
#########################################################
	
def rawpixel(image, label, fout, X, Y):

	
	image = cv2.resize(image, (X,Y) )
	#cv2.imshow("image", image )
	#cv2.waitKey(0)
	#cv2.destroyAllWindows()
	
	
	indice = 0
	fout.write(str(label) +  " ")
	for i in range(Y):
		#vet= []
		for j in range(X):
			if( image[i][j] > 128):
				v = 0
			else:
				v = 1	
			#vet.append(v)		
	
			fout.write(str(v)+" ")
			indice = indice+1

	fout.write("\n")
			

X = 20
Y = 20
arquivo = "dados.txt"

fout = open(arquivo,"w")

print (X,Y)

images = load_images('digits/data', fout, X,Y)

fout.close()

20 20
Loading images...
Extracting dummy features
Done!


In [12]:
#!/usr/bin/python
# -*- encoding: iso-8859-1 -*-

import sys
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn import preprocessing


def main(fname):

        # loads data
        print ("Loading data...")
        data = np.loadtxt(fname)
        X_data = data[:, 1:]
        y_data = data[:,0]

        print ("Spliting data...")
        X_train, X_test, y_train, y_test =  train_test_split(X_data, y_data, test_size=0.5, random_state = 5)

        #scaler = preprocessing.MinMaxScaler()
        #X_train = scaler.fit_transform(X_train)
        #X_test = scaler.fit_transform(X_test)

        # cria um kNN
        neigh = KNeighborsClassifier(n_neighbors=3, metric='chebyshev')

        print ('Fitting knn')
        neigh.fit(X_train, y_train)

        # predicao do classificador
        print ('Predicting...')
        y_pred = neigh.predict(X_test)

        # mostra o resultado do classificador na base de teste
        print ('Accuracy: ',  neigh.score(X_test, y_test))

        # cria a matriz de confusao
        cm = confusion_matrix(y_test, y_pred)
        print (cm)
        print(classification_report(y_test, y_pred))


#if __name__ == "__main__":
#        if len(sys.argv) != 2:
#                sys.exit("Use: knn.py <file>")

#        main(sys.argv[1])


In [13]:
main("dados.txt")

Loading data...
Spliting data...
Fitting knn
Predicting...
Accuracy:  0.108
[[  0   0  95   0   1   0   0   0   0   1]
 [  0   0  87   2   1   3   0   0   0   2]
 [  0   0 104   2   1   1   0   0   0   3]
 [  0   0 100   1   0   1   0   0   0   1]
 [  0   0  89   0   3   2   0   0   0   1]
 [  0   0  97   0   0   0   0   0   0   0]
 [  0   0 103   0   0   1   0   0   0   2]
 [  0   0  79   1   3   9   0   0   0   5]
 [  0   0  86   0   0   0   0   0   0   1]
 [  0   0 112   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        97
         1.0       0.00      0.00      0.00        95
         2.0       0.11      0.94      0.20       111
         3.0       0.17      0.01      0.02       103
         4.0       0.33      0.03      0.06        95
         5.0       0.00      0.00      0.00        97
         6.0       0.00      0.00      0.00       106
         7.0       0.00      0.00      0.00        97
      

/usr/lib/python3/dist-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
